// lib/src/bindings/winget_bindings.dart
//
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `dart run ffigen` from `native/src/winget_bridge.h`.
// Regenerate with: dart run ffigen --config ffigen.yaml
//
// ignore_for_file: type=lint
// ignore_for_file: avoid_positional_boolean_parameters
// ignore_for_file: non_constant_identifier_names

@ffi.DefaultAsset('package:winget_dart/src/winget_nc.dart')
library;

import 'dart:ffi' as ffi;

// ---------------------------------------------------------------------------
// Lifecycle
// ---------------------------------------------------------------------------

/// Initialize the bridge. Must be called once per process before any other
/// function. Passes the Dart VM's NativeApi.postCObject function pointer so
/// the bridge can send events back to Dart from the COM thread.
///
/// Returns 0 on success, non-zero HRESULT on failure.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>(symbol: 'wg_init')
external int wgInit(ffi.Pointer<ffi.Void> postCObject);

/// Connect to the Windows Package Manager COM server.
/// Returns an opaque handle (> 0) or a negative HRESULT on failure.
@ffi.Native<ffi.Int64 Function(ffi.Int64)>(symbol: 'wg_connect')
external int wgConnect(int replyPort);

/// Disconnect and release all COM references. Safe to call from any thread.
@ffi.Native<ffi.Void Function(ffi.Int64)>(symbol: 'wg_disconnect')
external void wgDisconnect(int handle);

/// Returns 1 if WinGet App Installer is present and reachable, 0 otherwise.
@ffi.Native<ffi.Int32 Function()>(symbol: 'wg_is_available')
external int wgIsAvailable();

// ---------------------------------------------------------------------------
// Catalogs
// ---------------------------------------------------------------------------

/// List all configured package catalogs.
/// Posts catalog JSON objects to replyPort, then {"done": true}.
@ffi.Native<ffi.Void Function(ffi.Int64, ffi.Int64)>(symbol: 'wg_list_catalogs')
external void wgListCatalogs(int handle, int replyPort);

// ---------------------------------------------------------------------------
// Search
// ---------------------------------------------------------------------------

/// Search for packages by name across all catalogs.
/// Posts package JSON objects to replyPort, then {"done": true}.
@ffi.Native<ffi.Void Function(ffi.Int64, ffi.Pointer<ffi.Char>, ffi.Int64)>(
    symbol: 'wg_search_name')
external void wgSearchName(
    int handle, ffi.Pointer<ffi.Char> query, int replyPort);

/// Search for a package by exact ID.
/// Posts {"pkg": {...}} or {"error": "..."} to replyPort.
@ffi.Native<
    ffi.Void Function(ffi.Int64, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>,
        ffi.Int64)>(symbol: 'wg_find_by_id')
external void wgFindById(int handle, ffi.Pointer<ffi.Char> packageId,
    ffi.Pointer<ffi.Char> catalogId, int replyPort);

// ---------------------------------------------------------------------------
// Installed packages
// ---------------------------------------------------------------------------

/// List all installed packages.
/// Posts package JSON objects to replyPort, then {"done": true}.
@ffi.Native<ffi.Void Function(ffi.Int64, ffi.Int64)>(
    symbol: 'wg_list_installed')
external void wgListInstalled(int handle, int replyPort);

// ---------------------------------------------------------------------------
// Simulate
// ---------------------------------------------------------------------------

/// Simulate install — resolve dependencies without installing.
/// Posts {"plan": {...}} or {"error": "..."} to replyPort.
@ffi.Native<
    ffi.Void Function(ffi.Int64, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>, ffi.Int64)>(symbol: 'wg_simulate_install')
external void wgSimulateInstall(
    int handle,
    ffi.Pointer<ffi.Char> packageId,
    ffi.Pointer<ffi.Char> catalogId,
    ffi.Pointer<ffi.Char> version,
    int replyPort);

/// Simulate upgrade (all packages or a specific one).
@ffi.Native<ffi.Void Function(ffi.Int64, ffi.Pointer<ffi.Char>, ffi.Int64)>(
    symbol: 'wg_simulate_upgrade')
external void wgSimulateUpgrade(
    int handle, ffi.Pointer<ffi.Char> packageId, int replyPort);

// ---------------------------------------------------------------------------
// Install / Upgrade / Uninstall
// ---------------------------------------------------------------------------

/// Install a package with progress events.
@ffi.Native<
    ffi.Void Function(
        ffi.Int64,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>,
        ffi.Int32,
        ffi.Int32,
        ffi.Int64)>(symbol: 'wg_install')
external void wgInstall(
    int handle,
    ffi.Pointer<ffi.Char> packageId,
    ffi.Pointer<ffi.Char> catalogId,
    ffi.Pointer<ffi.Char> version,
    int silent,
    int acceptAgreements,
    int replyPort);

/// Upgrade an installed package with progress events.
@ffi.Native<
    ffi.Void Function(ffi.Int64, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>,
        ffi.Int32, ffi.Int32, ffi.Int64)>(symbol: 'wg_upgrade')
external void wgUpgrade(
    int handle,
    ffi.Pointer<ffi.Char> packageId,
    ffi.Pointer<ffi.Char> version,
    int silent,
    int acceptAgreements,
    int replyPort);

/// Uninstall an installed package.
@ffi.Native<
    ffi.Void Function(ffi.Int64, ffi.Pointer<ffi.Char>, ffi.Int32,
        ffi.Int64)>(symbol: 'wg_uninstall')
external void wgUninstall(
    int handle, ffi.Pointer<ffi.Char> packageId, int silent, int replyPort);

// ---------------------------------------------------------------------------
// Updates check
// ---------------------------------------------------------------------------

/// List packages that have available upgrades.
/// Posts package JSON objects to replyPort, then {"done": true}.
@ffi.Native<ffi.Void Function(ffi.Int64, ffi.Int64)>(symbol: 'wg_get_updates')
external void wgGetUpdates(int handle, int replyPort);

// ---------------------------------------------------------------------------
// Cancellation
// ---------------------------------------------------------------------------

/// Request cancellation of any ongoing operation on the given handle.
@ffi.Native<ffi.Void Function(ffi.Int64)>(symbol: 'wg_cancel')
external void wgCancel(int handle);
